[package]
name = "ouch"
version = "0.4.2"
authors = ["Vinícius Rodrigues Miguel <vrmiguel99@gmail.com>", "João M. Bezerra <marcospb19@hotmail.com>"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/ouch-org/ouch"
license = "MIT"
keywords = ["decompression", "compression", "cli"]
categories = ["command-line-utilities", "compression", "encoding"]
description = "A command-line utility for easily compressing and decompressing files and directories."

[dependencies]
atty = "0.2.14"
bstr = { version = "1.6.0", default-features = false, features = ["std"] }
bzip2 = "0.4.4"
clap = { version = "4.3.23", features = ["derive", "env"] }
filetime = "0.2.22"
flate2 = { version = "1.0.27", default-features = false }
fs-err = "2.9.0"
gzp = { version = "0.11.3", default-features = false, features = ["snappy_default"] }
ignore = "0.4.20"
libc = "0.2.147"
linked-hash-map = "0.5.6"
lzzzz = "1.0.4"
once_cell = "1.18.0"
rayon = "1.7.0"
same-file = "1.0.6"
sevenz-rust = {version = "0.2.10", features = ["compress"]}
snap = "1.1.0"
tar = "0.4.40"
tempfile = "3.8.0"
time = { version = "0.3.26", default-features = false }
ubyte = { version = "0.10.3", default-features = false }
xz2 = "0.1.7"
zip = { version = "0.6.6", default-features = false, features = ["time"] }
zstd = { version = "0.12.4", default-features = false }

[target.'cfg(not(unix))'.dependencies]
is_executable = "1.0.1"

[build-dependencies]
clap = { version = "4.3.23", features = ["derive", "env", "string"] }
clap_complete = "4.3.2"
clap_mangen = "0.2.12"

[dev-dependencies]
assert_cmd = "2.0.12"
infer = "0.15.0"
parse-display = "0.8.2"
proptest = "1.2.0"
rand = { version = "0.8.5", default-features = false, features = ["small_rng", "std"] }
test-strategy = "0.3.1"

[features]
default = ["flate2/zlib", "gzp/deflate_zlib", "zip/deflate-zlib", "zstd/thin"]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
